description: ''
model:
    arch: ESPNet_L1b  # vssnet2, ssnet5, ESPNet, ESPNet_L1, ESPNet_Res, ESPNet_Res2, ESPNet_L1b
    change_arch: #[ESPNet_C_L1b, ESPNet_L1b]   #[ESPNet_C_L1b, ESPNet_L1b]  # change from X to Y architecture
    cell_type: 5  # 1..normal_conv, 2..1filter, 3..19filter, 4..t5-19filter, 5...normal_conv with peephole connections
    pq: [2,3]  # [2,3] 56.3% mIoU , [2,8] 61.4 % mIoU, on val-set paper Table 2g
    activation: 'prelu'  # 'prelu', 'lrelu', 'tanh' LSTM activation
    init: 'default'  # 'default', 'smart' LSTM init
    lstm_only: 0
    is_stateful: 1  # 0...stateless, 1...stateful # OLD:  0..stateless, 1..stateful_sn, 2..stateful_s1, 3...curr_timesteps - overlap
    state_init: learn # zero, rand, learn
    time_steps: 5 # ResNet
    filter_size: 5 # time_filter_size (LSTM or Res)
data:
    path: /home/user1/dataset/
    scale_size: #[512,1024]  #[256,512] [512,1024]  height,width
    augmentations: ['uniform', 'scale2x', 'hflip']  # 'scale2x', 'hflip']
    scale_dirs: [/home/user1/dataset/cityscapes_seq_DeepLabGT_sc1_3, #/home/user1/dataset/cityscapes_sc1_3, /home/user1/dataset/cityscapes_seq_DeepLabGT_sc1_3,
                 /home/user1/dataset/cityscapes_seq_DeepLabGT_sc4 ] #/media/user1/0bdbfbcf-61bc-4e16-acbf-7619c429d1c1/home/test/Data/dataset/cityscapes_sc4, /home/user1/dataset/cityscapes_seq_DeepLabGT_sc4]
training:
    GPU: 1  # 0..CPU, 1..GPU0, 2..GPU1
    # /media/user1/00882b03-e5e7-4839-8374-2a101fbf9a0f/home/user1/Data/dataset/cityscapes, cityscapes_video,
    # cityscapes_video_DeepLabGT, carla_seq_sc2, /home/user1/dataset/cityscapes_seq_DeepLabGT_sc2
    dataset: [ /home/user1/dataset/cityscapes_seq_DeepLabGT_sc2 ] #/media/user1/0bdbfbcf-61bc-4e16-acbf-7619c429d1c1/home/test/Data/dataset/cityscapes_sc2, /home/user1/dataset/cityscapes_seq_DeepLabGT_sc2]
    split: [train]
    nr_of_scenes: [2973] # 2964, all, [2975, 3598], 20%=745 2964
    shuffle_before_cut: [False]
    nr_of_sequences: [all] # 80, 156, all
    batch_size: 3
    loop_batch_size: 4
    shuffle: 1
    scene_group_size: 2973  #1488  # 50...4 GB RAM, 100.. 8 GB RAM
    crop_size: #[306,612] # [256,512] height,width
    crop_center: False
    time_interval: 2
    time_overlap: 0
    # loss function
    cross_entropy_lambda: 1
    weighted_ce: 1
    consistency_lambda: 10  #  3.0 makes sence because init-cross-entropy = 3
    consistency_function: sq_diff_true   #  sq_diff_true, sq_diff, abs_diff, argmax_pred, abs_diff_true, abs_diff_th20

    # training params
    train_iters: 10000
    l_rate: 1.0e-5
    momentum: 0.99
    #weight_decay: 0.0005
    visdom: False

    session: ESPNet_L1b
    load: ESPNet_L1b/stage4-t1o0bs10lbs0gs2970-aug-prelu-cons0-SF-lr-4-phase1/stage4-t1o0bs10lbs0gs2970-aug-prelu-cons0-SF-lr-4-phase1_bn_2219472_miou1.pkl
    save: stage5-t2o0bs3lbs4gs2973-aug-prelu-cons10SqDiffTrue-lr-5-phase1
    save_interval: 5
validation:
    GPU: 1
    dataset: [ /media/user1/0bdbfbcf-61bc-4e16-acbf-7619c429d1c1/home/test/Data/dataset/cityscapes_seq_DeepLabGT,
               /home/user1/dataset/cityscapes_seq_DeepLabGT,
               /home/user1/dataset/cityscapes]
    split: [train, val_short, val] # (val_short 125 scenes)
    augmentations: ['uniform']
    nr_of_scenes: [4, all, all]  # 500 val scenes
    shuffle_before_cut: [False, False, False]
    nr_of_sequences: [all, all, all]
    time_interval: 10
    input_size: [512, 1024]
    val_interval: 20  # 20 min
